name: test-login-service

run-name: Test login N.Âº${{ github.run_number }} hecho por ${{ github.actor }}
on:
  push:
    branches:
      - Login


jobs:
  # Tests unitarios  de Backend-Service
  unit-test-login-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/login-service
    steps:
      - name: ğŸ’»Checkout
        uses: actions/checkout@v3

      - name: ğŸ› ï¸Instalar dependecias
        run: npm install

      - name: ğŸ‘¾Test
        run: npm test

  # Subir imagen a DockerHub
  docker-push-login-service:
    runs-on: ubuntu-latest
    needs: unit-test-login-service
    defaults:
      run:
        working-directory: backend/login-service

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesiÃ³n en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Construir imagen de login-service
        run: docker build -t ${{ secrets.DOCKER_USER }}/mis-servicios:login-service-${{github.run_id}} .

      - name: Subir imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/mis-servicios:login-service-${{github.run_id}}