name: Login Test CI

run-name: Unit test login N.¬∫${{ github.run_number }} hecho por ${{ github.actor }}
on:
  push:
    branches:
      - SubirPDF


jobs:
  #hola
  # Tests unitarios  de Backend-Service
  unit-test-subirPDF-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/subirPDF-service
    steps:
      - name: üíªCheckout
        uses: actions/checkout@v3

      - name: üõ†Ô∏èInstalar dependecias
        run: npm install

      - name: üëæTest
        run: npm test

  # Pruebas de integraci√≥n con todos los servicios dockerizados
  docker-up-test:
    runs-on: ubuntu-latest
    needs: unit-test-subirPDF-service

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Levantar contenedores en segundo plano
        run: docker compose up -d

      - name: Esperar a que MySQL est√© listo
        run: |
          for i in {1..15}; do
            if docker exec mysql_db mysqladmin ping -uroot -p1234 --silent; then
              echo "‚úÖ MySQL listo"
              break
            fi
            echo "‚è≥ Esperando a MySQL..."
            sleep 2
          done

      - name: Esperar logs de subirPDF-service con conexi√≥n establecida
        run: |
          for i in {1..15}; do
            logs=$(docker logs subir_pdf_service 2>&1)
            if echo "$logs" | grep -q "Conexi√≥n establecida con la base de datos"; then
              echo "‚úÖ subirPDF-service conectado a la base de datos"
              exit 0
            fi
            echo "‚è≥ Esperando conexi√≥n desde subirPDF-service..."
            sleep 2
          done
          echo "‚ùå No se detect√≥ conexi√≥n en los logs"
          docker compose logs
          exit 1

      - name: Finalizar contenedores
        run: docker compose down

  # Subir imagen a DockerHub
  docker-push-login-service:
    runs-on: ubuntu-latest
    needs: docker-up-test
    defaults:
      run:
        working-directory: backend/login-service

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesi√≥n en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Construir imagen de login-service
        run: docker build -t ${{ secrets.DOCKER_USER }}/subirPDF-service:${{github.run_id}} .

      - name: Subir imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/subirPDF-service:${{github.run_id }}