name: test-subirPDF-service

run-name: Unit test login N.Âº${{ github.run_number }} hecho por ${{ github.actor }}
on:
  push:
    branches:
      - SubirPDF


jobs:
  #hola
  # Tests unitarios  de Backend-Service
  unit-test-subirPDF-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/subirPDF-service
    steps:
      - name: ğŸ’»Checkout
        uses: actions/checkout@v3

      - name: ğŸ› ï¸Instalar dependecias
        run: npm install

      - name: ğŸ‘¾Test
        run: npm test

  # Pruebas de integraciÃ³n con todos los servicios dockerizados
  docker-up-test:
    runs-on: ubuntu-latest
    needs: unit-test-subirPDF-service

    steps:
      - name: ğŸ’»Checkout
        uses: actions/checkout@v3

      - name: Levantar contenedores en segundo plano
        run: docker compose up -d

      - name: Esperar a que MySQL estÃ© listo
        run: |
          for i in {1..15}; do
            if docker exec mysql_db mysqladmin ping -uroot -p1234 --silent; then
              echo "âœ… MySQL listo"
              break
            fi
            echo "â³ Esperando a MySQL..."
            sleep 2
          done

      - name: Esperar logs de subirPDF-service con conexiÃ³n establecida
        run: |
          for i in {1..15}; do
            logs=$(docker logs subir_pdf_service 2>&1)
            if echo "$logs" | grep -q "ConexiÃ³n establecida con la base de datos"; then
              echo "âœ… subirPDF-service conectado a la base de datos"
              exit 0
            fi
            echo "â³ Esperando conexiÃ³n desde subirPDF-service..."
            sleep 2
          done
          echo "âŒ No se detectÃ³ conexiÃ³n en los logs"
          docker compose logs
          exit 1

      - name: Finalizar contenedores
        run: docker compose down

  # Subir imagen a DockerHub
  docker-push-subirPDF-service:
    runs-on: ubuntu-latest
    needs: docker-up-test

    defaults:
      run:
        working-directory: backend/subirPDF-service

    steps:
      - name: ğŸ’» Checkout repositorio
        uses: actions/checkout@v3

      - name: ğŸ” Iniciar sesiÃ³n en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          

      - name: ğŸ› ï¸ Construir imagen de subirpdf-service
        run: docker build -t ${{ secrets.DOCKER_USER }}/mis-servicios:subirpdf-service-latest .

      - name: ğŸ“¤ Subir imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/mis-servicios:subirpdf-service:latest
